# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 09:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=60, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='ideas_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'My Idea',
                'verbose_name_plural': 'My Ideas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tagulous_Ideas_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0,
                                              help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False,
                                                  help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='tagulous_ideas_tags',
            unique_together=set([('slug',)]),
        ),
        migrations.AddField(
            model_name='ideas',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, blank=True, force_lowercase=True,
                                                  help_text='Enter a comma-separated tag string', max_count=5,
                                                  to='core.Tagulous_Ideas_tags'),
        ),
        migrations.AddField(
            model_name='ideas',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
