# Generated by Django 2.1 on 2018-08-10 15:47

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Ideas', 'Idea')
    ]
