# Generated by Django 2.1 on 2018-08-10 16:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ideas',
            new_name='Idea',
        ),
        migrations.RenameModel(
            old_name='Tagulous_Ideas_tags',
            new_name='Tagulous_Idea_tags',
        ),
    ]
