# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='_Tagulous_Ideas_tags',
            new_name='Tagulous_Ideas_tags',
        ),
    ]
