# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 22:17
from __future__ import unicode_literals

from django.db import migrations
import tagulous.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='core._Tagulous_Ideas_tags'),
        ),
    ]
