# Generated by Django 2.1 on 2018-08-10 15:52

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('core', '0002_auto_20180810_1547'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tagulous_Ideas_tags',
            new_name='Tagulous_Idea_tags',
        ),
    ]
