# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161202_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='ideas',
            name='resume',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
