# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ideas_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='resume',
        ),
    ]
