# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_ideas_resume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ideas',
            options={'ordering': ['-created_at'], 'verbose_name': 'My Idea'},
        ),
    ]
