# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161206_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
