# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 00:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20161221_2351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='_Tagulous_Categories_tags',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
