# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20161225_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
