# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20161225_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ideas',
            name='likes',
        ),
    ]
