# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-27 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_ideas_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='slug',
            field=models.SlugField(max_length=60, null=True),
        ),
    ]
