# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20161227_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ideas',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
