# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170106_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ideas',
            name='title',
            field=models.CharField(default=2, max_length=60),
            preserve_default=False,
        ),
    ]
