# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20170106_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ideas',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
