language: python
python:
  - "3.5"
install:
  - pip install -q -r requirements.txt
before_script:
  - python contrib/secret_gen.py
  - python manage.py migrate
  - python manage.py collectstatic --no-input
script:
  - coverage run --source='myideas' manage.py test
before_install:
  - pip install coveralls
after_success:
  - coveralls