language: python
python:
  - "3.6"
services: postgresql
addons:
  postgresql: '9.6'
env:
   - DATABASE_URL=postgres://postgres@localhost/ideasdb
install:
  - pip install -q -r requirements.txt
before_script:
  - python contrib/secret_gen.py
  - psql -c "CREATE DATABASE ideasdb;" -U postgres
  - python manage.py migrate
  - python manage.py collectstatic --no-input
script:
  - coverage run --source='myideas' manage.py test
before_install:
  - pip install coveralls
after_success:
  - coveralls
